### ISSUE TITLE
Inspiral will not produce triggers if cluster-window > injection-window

### ISSUE THREAD

**Issue by cdcapano** [ligo-cbc/pycbc#246] opened 2015-09-03 15:37 UTC
I found that if the cluster-window argument is larger than the injection-window argument, pycbc_inspiral will produce no triggers. You can find an example command to make this happen on atlas8, at: ```/home/cdcapano/overlapStudies/early_aligo/flow30Hz/M_4_50_bbh/ians_new_banks/geom_bank_6_1100_stoch_filled_2step/pycbc_workflow/run_mkl/test/run_inspiral.sh```. In that script, you'll see that cluster-window is set to 4, while injection-window is set to 1. That command will produce no triggers. If I change injection-window to 3.9, I still get no triggers; if I set it to 4.1, I get triggers. To ensure that it is something to do with the cluster window, if I set the injection-window to 3.9, but change the cluster window to 3.5, I get triggers.

I'm not sure what's going on, but it appears to be due to something in threshold_and_cluster.

**Comment by duncan-brown** [comment] 2015-09-09 15:38
At the moment we should add an error message to prevent the user from doing this as it will not affect the all-sky search in O1.

**Comment by tdent** [comment] 2015-09-09 15:52
If the current code on master is known to be broken for some choices of parameters then I would hope we could get some guidance on that sent to the list (eg is it known, according to our best evidence, not to be broken for other choices) before too long.

**Comment by ahnitz** [comment] 2015-09-09 20:25
Josh,

 I think the issue is related to the fact that the slice that analyzed slice that is set for that segment will be shorter than the cluster window for that segment.  

Ian, 

What do you think of us just temporarily disabling the analyzed slice restriction for injections, until this issue is resolved. In any case, it only worked if there was a single injection per segment, which I think is too low a density going into the future. Is that all right with you? 

The trigger file size / post processing savings will still happen as that occurs at the end of the code.

**Comment by duncan-brown** [comment] 2015-09-10 13:28
Removed bug label, as merge #263 fixes this, but the underlying issues remains.

**Comment by ahnitz** [comment] 2015-10-26 14:41
Josh, is this still a problem? Or will the new clustering work if the slice is smaller than the injection-window? If so, we should close this.

**Comment by josh-willis** [comment] 2015-10-26 16:11
Logically it should work, and I just now did a run of inspiral on a single-template bank (what we were using when tracking down the BBH missed injection) and it found the same SNR and end time with a 512 s window, so I'm closing this.

**Comment by ahnitz** [comment] 2015-10-26 16:12
Great!

**Closed by josh-willis** 2015-10-26 16:11 UTC
