### ISSUE TITLE
correlate parallel broken when used in simple usage

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#123] opened 2015-06-30 18:45 UTC
I have reverted the correlate function (not the Correlator, so pycbc_inspiral still used it), so the match function will use the old correlate_inline. 

(from Riccardo)

Hi All,

I'm trying to compute overlaps in pycbc.
While in the past it has been as straightforward as

hp, hc = get_td_waveform(coa_phase=phiRef, delta_t=dT, mass1=m1,
mass2=m2, f_lower=fLow, distance=dist, inclination=inc,
approximant=apprxStr)
overlap, idxM = match(hp, hc, low_frequency_cutoff=fLow)

using present master version I hit the following error:
----------------------------------------------------------------------------------
/tmp/1000_python27_compiled/sc_ce6a0f08bc653d0518ec8e7d5816a62311.cpp:
In function ‘PyObject* compiled_func(PyObject*, PyObject*)’:
/tmp/1000_python27_compiled/sc_ce6a0f08bc653d0518ec8e7d5816a62311.cpp:1070:82:
error: cannot convert ‘std::complex<double>*’ to
‘std::complex<float>*’ for argument ‘1’ to ‘void
ccorrf_parallel(std::complex<float>*, std::complex<float>*,
std::complex<float>*, uint32_t, uint32_t)’
     ccorrf_parallel(htilde, stilde, qtilde, (uint32_t) arrlen,
(uint32_t) segsize);

           ^
/tmp/1000_python27_compiled/sc_ce6a0f08bc653d0518ec8e7d5816a62311.cpp:
In function ‘PyObject* compiled_func(PyObject*, PyObject*)’:
/tmp/1000_python27_compiled/sc_ce6a0f08bc653d0518ec8e7d5816a62311.cpp:1070:82:
error: cannot convert ‘std::complex<double>*’ to
‘std::complex<float>*’ for argument ‘1’ to ‘void
ccorrf_parallel(std::complex<float>*, std::complex<float>*,
std::complex<float>*, uint32_t, uint32_t)’
     ccorrf_parallel(htilde, stilde, qtilde, (uint32_t) arrlen,
(uint32_t) segsize);

           ^
Traceback (most recent call last):
  File "checkEOBNRv2.py", line 54, in <module>
    overlap, idxM = match(hpM_tilde, hpM_tilde, low_frequency_cutoff=fLow)
  File "/home/riccardo/lvc/lscsoft/opt/EOBNRv2review/pycbc/lib/python2.7/site-packages/pycbc/filter/matchedfilter.py",
line 677, in match
    high_frequency_cutoff, v1_norm, out=_snr)
  File "/home/riccardo/lvc/lscsoft/opt/EOBNRv2review/pycbc/lib/python2.7/site-packages/pycbc/filter/matchedfilter.py",
line 557, in matched_filter_core
    correlate(htilde[kmin:kmax], stilde[kmin:kmax], _qtilde[kmin:kmax])
  File "<string>", line 2, in correlate
  File "/home/riccardo/lvc/lscsoft/opt/EOBNRv2review/pycbc/lib/python2.7/site-packages/pycbc/scheme.py",
line 172, in scheming_function
    return schemed_fn(*args, **kwds)
  File "/home/riccardo/lvc/lscsoft/opt/EOBNRv2review/pycbc/lib/python2.7/site-packages/pycbc/filter/simd_correlate.py",
line 400, in correlate_parallel
    support_code = corr_support, auto_downcast = 1)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/inline_tools.py",
line 361, in inline
    **kw)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/inline_tools.py",
line 491, in compile_function
    verbose=verbose, **kw)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/ext_tools.py",
line 373, in compile
    verbose=verbose, **kw)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/build_tools.py",
line 297, in build_extension
    raise e
scipy.weave.build_tools.CompileError: error: Command "c++ -pthread
-fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -fPIC
-I/usr/lib/python2.7/dist-packages/scipy/weave
-I/usr/lib/python2.7/dist-packages/scipy/weave/scxx
-I/usr/lib/python2.7/dist-packages/numpy/core/include
-I/usr/include/python2.7 -c
/tmp/1000_python27_compiled/sc_ce6a0f08bc653d0518ec8e7d5816a62311.cpp
-o /tmp/scipy-riccardo-XzpoDg/python27_intermediate/compiler_8855277b295f576c423c618665ded9a0/tmp/1000_python27_compiled/sc_ce6a0f08bc653d0518ec8e7d5816a62311.o
-march=native -O3 -w -fopenmp" failed with exit status 1
------------------------------------------------------------------
Can anyone tell me what I am doing wrong?
Cheers,

Riccardo

P.S. I'm sorry I can't retrieve the git hash of the pycbc that worked
for me, but it should be master from last April or so.

**Comment by josh-willis** [comment] 2015-06-30 18:50
Approved, please merge.

**Comment by ahnitz** [comment] 2015-06-30 18:51
I've already pushed the fix, so that master isn't broken. I just opened the issue so that we could later figure out what was happening and why.

**Comment by josh-willis** [comment] 2015-06-30 19:14
Well it's easy to figure out what the problem is: the parallel version of correlate (the code that is in simd_correlate) only supports single precision.

Since it would be a lot of work to add, I would prefer to keep it this way unless there is a use case where double precision correlate needs the performance benefit of parallel and simd.  Otherwise I think the fix you pushed should simply be sufficient to close this issue.

**Closed** 2015-07-01 20:17 UTC
