### ISSUE TITLE
Workflow is broken if X509_USER_PROXY is set

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#704] opened 2016-02-16 09:28 UTC
Currently PyCBC workflows will fail if the environment variable X509_USER_PROXY is set. As this is sourced on all LVC clusters on log-in, the only case where this does _not_ fail is when pycbc_submit_dax runs `unset X509_USER_PROXY` before running `ligo-proxy-init`. The following cases will cause failures unless the user runs `unset X509_USER_PROXY` manually:
- Submission of a workflow using --no-submit option
- Submission of a workflow using --no-proxy option
- Re-submission of a failed workflow

**Comment by spxiwh** [comment] 2016-02-25 15:51
Just bumping this, as it really needs fixing.

**Comment by duncan-brown** [comment] 2016-04-05 22:41
The solution to this is to make sure that the ``X509_USER_PROXY`` profile is set in the site local catalog. To fix this, make sure that when the site catalog is created, it contains the profile
```
<profile namespace="pegasus" key="X509_USER_PROXY" >/tmp/x509_uXXX</profile>
```
replacing ``XXX`` with the user's uid. Since ``ligo-proxy-init`` always creates the credential in at this location, the workflow will never mistakenly pick up a short-term ssh-generated credential. 

In principle this just needs a simple patch to https://github.com/ligo-cbc/pycbc/blob/master/pycbc/workflow/pegasus_files/local-site-template.xml to add
```
<profile namespace="pegasus" key="X509_USER_PROXY" >/tmp/x509_u${UID}</profile>
```
and a patch https://github.com/ligo-cbc/pycbc/blob/master/bin/pycbc_submit_dax to set ``$UID`` before it writes the site catalog.

@spxiwh want to try this and see if it works?

**Comment by duncan-brown** [comment] 2016-04-05 22:47
@spxiwh side note, I think this is a problem of *generating* a workflow with a temporary sshd-generated credential. This then gets embedded in the ``.sub`` files, but gets deleted when you log out. So the workflow then fails. If you explicitly give the path to the persistent one generated by ```ligo-proxy-init``` in the site catalog, then this shouldn't happen.

Of course, we still have the problem that you need to ```ligo-proxy-init``` every 72 hours, but the auth people are working on that.

**Comment by spxiwh** [comment] 2016-04-07 09:04
Adding

``` <profile namespace="pegasus" key="X509_USER_PROXY" >/tmp/x509up_u2174</profile>```

makes no change to the current behaviour (ie. the code still fails in all of the cases listed at the top). Specifically, the code still fails if the X509_USER_PROXY environment variable is set, and fails if it doesn't. I'm not really sure what this fix was expected to do that would solve the problem? ...

If X509_USER_PROXY environment variable is set, the pegasus start-up script (pegasus-kickstart I think, but it may be something else in the .sh files that are the pegasus "executables"), checks if the file actually exists. The file *does not* exist on any node, it is /tmp/x509up_u2174 and that only exists on the head node. Therefore all jobs fail.

Without this variable set all jobs run fine ... including the segment-query jobs (which run in local universe and seem to find the proxy fine, even without X509_USER_PROXY set).  .... The fact that jobs are *not* failing when adding this pegasus namespace profile suggests that it is doing nothing.

**Comment by duncan-brown** [comment] 2016-04-07 18:10
@spxiwh can you point me to an actual failing run? I have not been able to reproduce this.

**Comment by duncan-brown** [comment] 2016-08-20 19:15
@stevereyes01 we should check this in 1.5.x

**Comment by duncan-brown** [comment] 2016-08-26 18:57
This might be fixed by https://jira.isi.edu/browse/PM-1099

**Comment by duncan-brown** [comment] 2016-11-04 20:08
Fixed by https://github.com/ligo-cbc/pycbc/pull/1192

**Closed by duncan-brown** 2016-11-04 20:08 UTC
Labels: bug
