### ISSUE TITLE
pycbc_condition_strain cannot be read by FrChannels

### ISSUE THREAD

**Issue by ahnitz** [ligo-cbc/pycbc#945] opened 2016-06-27 15:02 UTC
We are noticing some problems reading the output of pycbc_condition_strain. In particular the following scripts outputs a file which cannot be read by FrChannels nor pycbc_inspiral. 

```
pycbc_condition_strain\
   --sample-rate 16384 \
   --channel-name  H1:DCS-CALIB_STRAIN_C01\
   --gps-start-time 1135664800\
   --gps-end-time   1135698459\
   --frame-type H1_HOFT_C01\
   --output-strain-file "H-H1_DCS-CALIB_STRAIN_C01_V1-1135664800-4096.gwf"\
   --pad-data 0\
   --strain-high-pass 20
```

```
*** Error reading frame from file H-H1_DCS-CALIB_STRAIN_C01_V1-1135664800-4096.gwf
*** FrError: in FrError FrRead error: EOF reached
*** FrError: in FrReadVD error reading bank
*** FrError: in FrVectRead : Record length error: nBytes=116792536 nBytesR=3251 length=116785262
```

Is anyone else able to reproduce this issue?

**Comment by titodalcanton** [comment] 2016-06-27 15:37
I know Bernd has been able to produce SFTs out frame files written by pycbc_condition_strain. Did you try feeding the file to utilities like FrDump, framedump, framecpp_verify etc?

**Comment by cmbiwer** [comment] 2016-06-27 15:42
@ahnitz I see the same issue.

@titodalcanton ``FrDump`` has a failure.

**Comment by titodalcanton** [comment] 2016-06-27 15:45
Can you also try reading one of the frame files on Atlas in this directory: `~/projects/pycbc/frame_gating_for_map/all_o1/output_strain`. Those are also genereated by pycbc_condition_strain.

**Comment by cmbiwer** [comment] 2016-06-27 15:52
Using a smaller set of data (2048 seconds) I'm able to use ``FrChannels`` on the output file of ``pycbc_condition_strain``.

**Comment by titodalcanton** [comment] 2016-06-27 15:52
FrChannels seems to work on my frame files at the path indicated above.

**Comment by titodalcanton** [comment] 2016-07-11 15:10
Confirmed, the problem only happens when `--sample-rate` is either not specified or set to 16384. The resulting frame file is suspiciously small and it makes `framecpp_query` segfault. Will take a look at what's going on in `pycbc_condition_strain`.

**Comment by titodalcanton** [comment] 2016-07-11 18:17
I also found that either using `--single` or processing a shorter amount of time produces correct frames even at the original sample rate. `pycbc_condition_strain` and `pycbc/frame.py` seem to be doing the right thing. The problem seems to be a bug in lalframe related to how much data is being written...

**Comment by titodalcanton** [comment] 2016-07-11 20:44
I wrote a small test script to reproduce the issue and posted the problem on Redmine:

https://bugs.ligo.org/redmine/issues/4484

**Comment by titodalcanton** [comment] 2016-07-26 15:47
After commit ba1d52a417, lalframe catches the issues and throws an error, so the surprising behavior is gone; closing.

Still, we can't write frame files as huge as theoretically possible until framelib is fixed (or lalframe is built and configured for framec). If we want that ability now, let's ask that in another issue.

**Closed by titodalcanton** 2016-07-26 15:47 UTC
