### ISSUE TITLE
pycbc_coinc_statmap fails when processing .hdf coinc-files

### ISSUE THREAD

**Issue by juancalderonbustillo** [ligo-cbc/pycbc#641] opened 2015-11-27 15:01 UTC
When running on Recolored s6 data, the output of 

(*****)

logging.info("Loading coinc triggers")
d = pycbc.io.StatmapData(files=args.coinc_files)
logging.info("We have %s triggers" % len(d.stat))
fore_locs = d.timeslide_id == 0
ft1, ft2 = d.time1[fore_locs], d.time2[fore_locs] in pycbc_coinc_statmap

(*****)
yields ft1= [ ] and ft2 = [ ], which makes the full run to fail.  This is happening since mid-October. Previously, the runs would finish, giving, for example, ft1 = [  9.66609307e+08   9.66609307e+08   9.66609307e+08   9.66609307e+08 9.66609307e+08   9.66609307e+08] and similarly for ft2. 

fore_locs gives the same result in both cases. Thus, the problem arises when executing d.time1[fore_locs].

Work directory is /local/user/juan.bustillo/pycbc-tmp.Zj9CRtXULq/work in atlas.

**Comment by spxiwh** [comment] 2015-11-27 15:12
Can you put the full error message here? This seems to be an issue that the code is failing when there are no foreground triggers, and I did run tests ~month ago to verify that the code *does* run in this case, so I am surprised?

Are you using the latest code version?

**Comment by juancalderonbustillo** [comment] 2015-11-27 15:23
The full command and error messages are:

site        : local

hostname    : mga9205.atlas.local

executable  : /home/juan.bustillo/pycbc-dev/bin/pycbc_coinc_statmap

arguments   :   --veto-window   0.100   --cluster-window   10.0
--coinc-files
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_0-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_1-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_2-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_3-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_4-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_5-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_6-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_7-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_8-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_9-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_10-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_11-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_12-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_13-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_14-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_15-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_16-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_17-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_18-966384015-102800.hdf
H1L1-COINC_FULL_DATA_FULL_CUMULATIVE_CAT_12H_19-966384015-102800.hdf
--output-file
H1L1-STATMAP_FULL_DATA_FULL_CUMULATIVE_CAT_12H-966384015-102800.hdf

exitcode    : 1

working dir :
/home/juan.bustillo/standard_pycbc_run/trial/run/work/main_ID0000001

--------Task #1 - statmap-FULL_DATA_FULL-H1L1_ID15 - ID0000575 -
stdout---------


---Task #1 - statmap-FULL_DATA_FULL-H1L1_ID15 - ID0000575 - Kickstart
stderr----

Traceback (most recent call last):

  File "/home/juan.bustillo/pycbc-dev/bin/pycbc_coinc_statmap", line 4, in
<module>

    __import__('pkg_resources').run_script('PyCBC===ee4c62',
'pycbc_coinc_statmap')

  File
"/home/juan.bustillo/pycbc-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 735, in run_script

    self.require(requires)[0].run_script(script_name, ns)

  File
"/home/juan.bustillo/pycbc-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 1652, in run_script

    exec(code, namespace, namespace)

  File
"/home/juan.bustillo/pycbc-dev/lib/python2.7/site-packages/PyCBC-ee4c62-py2.7.egg/EGG-INFO/scripts/pycbc_coinc_statmap",
line 39, in <module>

    v1 = veto.indices_within_times(d.time1, veto_start, veto_end)

  File
"/home/juan.bustillo/pycbc-dev/lib/python2.7/site-packages/PyCBC-ee4c62-py2.7.egg/pycbc/events/veto.py",
line 134, in indices_within_times

    return tsort[numpy.hstack(numpy.r_[s:e] for s, e in zip(left, right))]

  File
"/home/juan.bustillo/pycbc-dev/lib/python2.7/site-packages/numpy/core/shape_base.py",
line 274, in hstack

    if arrs[0].ndim == 1:

IndexError: list index out of range


I forked an editable version (which I believe is the latest editable one?)
of pycbc from git@github.com:juancalderonbustillo/pycbc.git

Is there a way I can provide some version number or similar?


Thanks.

2015-11-27 16:12 GMT+01:00 spxiwh <notifications@github.com>:

**Comment by spxiwh** [comment] 2015-11-27 15:29
Thanks, from this information I can confirm that the version of the code you are using does not include the fix that (I think Tito) put in to fix this. Try using a more recent version of the code.

**Comment by juancalderonbustillo** [comment] 2015-11-27 15:31
So, I forked this version a week ago. Should I use a non editable version?
Thx.

2015-11-27 16:29 GMT+01:00 spxiwh <notifications@github.com>:

**Comment by spxiwh** [comment] 2015-11-27 15:35
The commit you are missing in

```
/home/juan.bustillo/pycbc-dev/lib/python2.7/site-packages/PyCBC-ee4c62-py2.7.egg/pycbc/events/veto.py
```

is this one from August 30

```
commit 2f8bb4a913a73e6baffe4040240f435099ac0e31
Author: Alexander Harvey Nitz <ahnitz@syr.edu>
Date:   Sun Aug 30 12:59:04 2015 -0400

    allow no foreground events
```

What do you mean by "non-editable" version?

**Comment by juancalderonbustillo** [comment] 2015-11-27 15:40
Thanks,

from the instructions in
http://ligo-cbc.github.io/pycbc/latest/html/install.html

i assumed there were editable and non-editable versions. But one can
actually use the -e when isntalling pycbc option for creating the src/pycbc
folder and make edits.

Thx.



2015-11-27 16:35 GMT+01:00 spxiwh <notifications@github.com>:

**Comment by ahnitz** [comment] 2015-11-29 14:22
I'm closing this as it seems this was a  case of picking up an old version before the bug was fixed. If this isn't the case please feel free to re-open.

**Closed by ahnitz** 2015-11-29 14:22 UTC
