### ISSUE TITLE
M2Crypto hits a library error when installed on atlas with the install script

### ISSUE THREAD

**Issue by tdent** [ligo-cbc/pycbc#504] opened 2015-10-19 10:14 UTC
I have repeatedly seen an error as follows when using the pycbc install script on atlas (atlas9 and atlas8). 

    $ ligolw_dq_query_dqsegdb --help

    ligo_data_find requires the M2Crypto and cjson
    modules.

    On CentOS 5 and other RHEL based platforms
    these packages are available from the EPEL
    repository by doing

    yum install m2crypto
    yum install python-cjson

    For Debian Lenny these packages are available
    by doing

    apt-get install python-m2crypto
    apt-get install python-cjson

    Mac OS X users can find these packages in
    MacPorts.

    /home/tdent/pycbc-dev/local/lib/python2.7/site-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv2_method

The first part of the error message is boilerplate which assumes that the problem must be due to my not having packages installed, in fact the error is that the packages are buggy.  
Error may be related to this SO thread : http://stackoverflow.com/questions/10547332/install-m2crypto-on-a-virtualenv-without-system-packages 
I am able to get over the error and run the dqsegdb codes successfully by copying the system installed M2Crypto folder into my virtualenv site-packages (fix suggested by ANitz).

**Comment by duncan-brown** [comment] 2015-10-19 18:54
Assigning to @ahnitz as I think someone needs to sit next to Tom and help him with this. I can't reproduce the error.

**Comment by duncan-brown** [comment] 2015-10-26 14:25
@ahnitz @tdent is this still an issue? Can it be closed?

**Comment by tdent** [comment] 2015-10-26 14:41
Yes, AFAIK.  I was only able to work around it by uninstalling from the virtualenv and copying in the system version to my virtualenv dir.

**Comment by duncan-brown** [comment] 2015-11-10 20:54
New new information on this, as I can build fine on atlas, so I am closing. Please re-open if the issue comes back.

**Closed by duncan-brown** 2015-11-10 20:54 UTC

**Comment by tdent** [comment] 2015-11-11 09:53
Did you expect any new information?  I have been using the hacked (copied over) system M2Crypto for >2 weeks now, so I guess it can be considered stable.
