### ISSUE TITLE
CPU matched filter ignores number of threads argument

### ISSUE THREAD

**Issue by cdcapano** [ligo-cbc/pycbc#219] opened 2015-08-26 13:36 UTC
When I use the matched filter engine with the processing scheme set to CPU on Atlas, it ignores the num threads argument that is set in scheme.from_cli. For instance, if I run pycbc_inspiral with:
```
pycbc_inspiral {some arguments}  --processing-scheme cpu
```
Several parallel threads will get launched when it hits the filtering part (observed by running htop while the job while was running). This is true both on the head node and on the cluster nodes. If I manually try to set the number of threads with:
```
pycbc_inspiral {some arguments}  --processing-scheme cpu:1
```
It still ignores it. Oddly, however, if I manually export OMP_NUM_THREADS prior to running, then the number of threads does respect what I set it to (though still ignoring whatever from_cli is set to). For instance, if I do:
```
export OMP_NUM_THREADS=3
pycbc_inspiral {some arguments}  --processing-scheme cpu:1
```
The number of parallel threads that are launched is 3. If I repeat the same thing, but manually setting NUM_THREADS to 1, the number of threads is 1.

I don't know why this is happening. If I set the processing scheme to mkl, it does respect the number of threads that are set in from_cli. Looking at scheme.py, I see that the MKLScheme inherits from CPUScheme, the code that sets the environment must be working properly. Is it possible that omp somehow doesn't respect python's os.environ?

In any event, until this is fixed, 'cpu' should not be used (at least on atlas; maybe it's ok on another cluster), as it can cause a job to hog resources when running in a dag. I realize mkl is probably better anyway, but cpu is the default that is used if processing-scheme is not specified. This can cause issues for new users.

**Comment by spxiwh** [comment] 2015-08-26 13:43
Hi Collin,

I use this setup regularly on vulcan (same hardware as atlas) and have never observed this.

My suspicion would be that the waveform generation in lalsimulation is ignoring this. Have you compiled lalsimulation with openmp support? Do you still see > 100% CPU usage if using a waveform that does not support multi-threading (I think TaylorT2 does not?).

**Comment by lppekows** [comment] 2015-08-26 14:35
Hi Collin,

I’m not seeing this on atlas8.  The version I’m using is

  $ pycbc_inspiral --version
  Branch: None Tag: v1.1.0 Id: dc5547098e9df1153bf134795a38c0409650cd34

Running with --verbose reports

  2015-08-26 16:14:06,704 Running with CPU support: 1 threads

Running under strace and grepping for fftw shows I’m loading

  open("/usr/lib/x86_64-linux-gnu/libfftw3.so.3.3.2", O_RDONLY) = 9

and grepping for omp shows I’m loading

  open("/usr/lib/x86_64-linux-gnu/libfftw3_omp.so.3.3.2", O_RDONLY) = 3
  open("/usr/lib/x86_64-linux-gnu/libgomp.so.1", O_RDONLY) = 3

and there are no OMP-related settings in my environment.

Could you check for these same things just to see if there’s anything different?


On Aug 26, 2015, at 9:36 AM, Collin Capano <notifications@github.com<mailto:notifications@github.com>> wrote:


When I use the matched filter engine with the processing scheme set to CPU on Atlas, it ignores the num threads argument that is set in scheme.from_cli. For instance, if I run pycbc_inspiral with:

pycbc_inspiral {some arguments}  --processing-scheme cpu


Several parallel threads will get launched when it hits the filtering part (observed by running htop while the job while was running). This is true both on the head node and on the cluster nodes. If I manually try to set the number of threads with:

pycbc_inspiral {some arguments}  --processing-scheme cpu:1


It still ignores it. Oddly, however, if I manually export OMP_NUM_THREADS prior to running, then the number of threads does respect what I set it to (though still ignoring whatever from_cli is set to). For instance, if I do:

export OMP_NUM_THREADS=3
pycbc_inspiral {some arguments}  --processing-scheme cpu:1


The number of parallel threads that are launched is 3. If I repeat the same thing, but manually setting NUM_THREADS to 1, the number of threads is 1.

I don't know why this is happening. If I set the processing scheme to mkl, it does respect the number of threads that are set in from_cli. Looking at scheme.py, I see that the MKLScheme inherits from CPUScheme, the code that sets the environment must be working properly. Is it possible that omp somehow doesn't respect python's os.environ?

In any event, until this is fixed, 'cpu' should not be used (at least on atlas; maybe it's ok on another cluster), as it can cause a job to hog resources when running in a dag. I realize mkl is probably better anyway, but cpu is the default that is used if processing-scheme is not specified. This can cause issues for new users.

**Comment by cdcapano** [comment] 2015-08-26 19:00
Hi Larne,

Thanks for taking a look. I also ran with verbose, and yes, it reports "Running with CPU support: 1 threads", but that's not what I'm seeing when I run htop. 

To make sure I'm using a correct version, I just pulled from master and did a fresh install. Running version I get:
```
[cdcapano@atlas8 test]$ pycbc_inspiral --version
Branch: master Tag: None Id: a5975eb67f572b1dd1888a963e4b9a4973379ac7 Builder:
Collin Capano <collin.capano@ligo.org> Build date: 2015-08-26 17:44:36 +0000
Repository status is CLEAN: All modifications committed
```
I still get the same behavior. I ran strace, and I do get similar things as you when I grep for fftw:
```
open("/usr/lib/x86_64-linux-gnu/libfftw3f_omp.so.3.3.2", O_RDONLY) = 4
```
When I grep for omp, I do also get:
```
open("/usr/lib/x86_64-linux-gnu/libfftw3_omp.so.3.3.2", O_RDONLY) = 4
open("/usr/lib/x86_64-linux-gnu/libgomp.so.1", O_RDONLY) = 14
```
However, in both cases, I get a bunch of other stuff also. If you'd like to see my full strace output, it's on atlas8 at:
```
/home/cdcapano/overlapStudies/early_aligo/flow30Hz/M_4_50_bbh/ians_new_banks/geom_bank_6_1100_stoch_filled_2step/pycbc_workflow/run_mkl/test/strace.out
```
In that directory you'll also find the command I am using for pycbc_inspiral, in run_inspiral-cpu.sh.

I checked if my OMP_NUM_THREADS variable is set prior to running, and it is not. I'm not sure how to check for other omp environment variables though.

I'm not sure the issue is with fftw. The code in question are these lines of matchedfilter_cpu.py:

https://github.com/ligo-cbc/pycbc/blob/master/pycbc/filter/matchedfilter_cpu.py#L39-L53

Specifically, the behavior I am seeing is if I run ```htop -u cdcapano``` in another window while pycbc_inspiral is running, I initially have:
```
 4294 cdcapano   20   0  982M  619M 23864 R 99.0  0.5  0:23.65 |              `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral --sn
```
Right around the point the verbose message says "Filtering templates {x} / {y}", htop suddenly shows pycbc_inspiral launching several sub-processes like so:
```
 4625 cdcapano   20   0  987M  529M 27960 R 245.  0.4  2:28.59 |              `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral --sn
 4900 cdcapano   20   0  987M  529M 27960 S 12.0  0.4  0:02.49 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4899 cdcapano   20   0  987M  529M 27960 S 13.0  0.4  0:02.56 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4898 cdcapano   20   0  987M  529M 27960 R 13.0  0.4  0:02.52 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4897 cdcapano   20   0  987M  529M 27960 S 13.0  0.4  0:02.54 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4896 cdcapano   20   0  987M  529M 27960 R 13.0  0.4  0:02.55 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4895 cdcapano   20   0  987M  529M 27960 S 13.0  0.4  0:02.55 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4894 cdcapano   20   0  987M  529M 27960 S 13.0  0.4  0:02.53 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4893 cdcapano   20   0  987M  529M 27960 S 13.0  0.4  0:02.58 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4892 cdcapano   20   0  987M  529M 27960 R 13.0  0.4  0:02.54 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4891 cdcapano   20   0  987M  529M 27960 R 12.0  0.4  0:02.53 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
 4890 cdcapano   20   0  987M  529M 27960 S 12.0  0.4  0:02.55 |                 `- /usr/bin/python /home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral -
```
If I set OMP_NUM_THREADS by hand before I run, however, the number of subprocesses = the number of threads I set. Also, if I run with processing-sheme = mkl, the number of subproceses remains 1.

Do you see similar behavior?
Collin

**Comment by cdcapano** [comment] 2015-08-26 19:02
Hi Ian,

No, I didn't install lalsuite with omp support (at least I don't think I did; I'm guessing you need to add an extra command for that to happen). Also, if it was due to lalsimulation, why would changing pycbc_inspiral's processing-scheme command to mkl affect it?

Thanks,
Collin

**Comment by lppekows** [comment] 2015-08-26 19:48
Hi Collin,

I was a little suspicious of fftw because you see different behavior with mkl, but it could be in other parallelized code.  In any case, when I run htop never reports more than a single thread even once it gets  to the filtering.

I don't know if it's relevant, but It does look like we're running different versions of lalsuite since when I try your command I get

XLAL Error - XLALSimInspiralDecomposeWaveformString (LALSimInspiral.c:4656): Invalid waveform string `SEOBNRv2'.
XLAL Error - XLALGetOrderFromString (LALSimInspiral.c:4726): Cannot parse approximant from string `SEOBNRv2'.

I built lalsuite from 5e6666167b1fe4d7b4289ba94d764adf5398d675

**Comment by ahnitz** [comment] 2015-08-26 22:49
Collin, 

I'll take a look at this issue when I get a chance, but I did try the following quickly on my laptop. I use the following script.
```
python -m cProfile -o gauss.log `which pycbc_inspiral` \
--snr-threshold 5.0 \
--newsnr-threshold 5.0 \
--bank-file bank.xml \
--low-frequency-cutoff 40 \
--sample-rate 4096 \
--approximant SPAtmplt \
--cluster-method window \
--cluster-window 1 \
--chisq-bins 128 \
--psd-estimation median \
--psd-segment-length 16 \
--psd-segment-stride 8 \
--gps-start-time 100000000 \
--gps-end-time   100002240 \
--strain-high-pass 30 \
--pad-data 8 \
--channel-name H1:FAKE-STRAIN \
--fake-strain iLIGOModel \
--fake-strain-seed=1 \
--segment-length 512 \
--segment-start-pad 16 \
--segment-end-pad 64 \
--processing-scheme cpu:1 \
--fftw-measure-level 0 \
--output test.hdf \
--verbose 
```

When I run this with htop on sugar or my laptop it uses exactly the correct number of threads. I'll check if that is true on atlas as well.

**Comment by ahnitz** [comment] 2015-08-27 02:18
Collin, I have been able to reproduce this, but I am so far at a loss as to why this is happening. The only clue I have is that this appears to be isolated to ATLAS, I can run the same script on CIT, SUGAR, and my personal machines and all works as expected. On ATLAS it looks like the internal environment variable set to control threading is ignored completely, but it still works if set outside the script, which makes no sense to me. 

We set the number of threads here. I don't know why it doesn't work on atlas. 
https://github.com/ligo-cbc/pycbc/blob/master/pycbc/scheme.py#L126

What is stranger is that it does work for MKL, for which we use exactly the same mechanism for controlling threading, the "OMP_NUM_THREADS" variable. My only guess is that the version of OpenMP on Atlas is different and the library itself is treating the variable different than it used to, breaking our control mechanism. 

Josh, do you have any ideas off the top of your head.? 

For now, please either set OMP_NUM_THREADS explicitly before running, or use MKL.

**Comment by ahnitz** [comment] 2015-08-27 02:21
The only thing I'll add is that the version of GCC on my machine and python are later than ATLAS's so I doubt that that alone is the issue. Perhaps the way it is configured for debian?

**Comment by lppekows** [comment] 2015-08-27 02:46
Hi all,

The _lalsimulation.so that Collin's strace output names depends on libgomp:

$ grep _lalsimulation.so strace.out 
open("/usr/lib/python2.7/dist-packages/lalsimulation/_lalsimulation.so", O_RDONLY) = 13

$ ldd /usr/lib/python2.7/dist-packages/lalsimulation/_lalsimulation.so | grep gomp
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fb1ee8bd000)

However, mine doesn't:

$ ldd /home/lppekows/local/lib/python2.7/site-packages/lalsimulation/_lalsimulation.so  | grep gomp
(nothing)

So, is it possible that for Collin libgomp comes in during the first imports in pycbc_inspiral, the library looks for the variable at load time (before it's been set) and then doesn't see the change?  Whereas for me the library is  loaded later, after the variable has been set?  I think mkl uses an openmp library from intel which would also get loaded after the environment variable has been set.

**Comment by ahnitz** [comment] 2015-08-27 02:54
Ok, interesting. I'll note, that for my test on ATLAS I also used the system lalsimulation.

**Comment by lppekows** [comment] 2015-08-27 03:16
I can also reproduce the problem if I point to the system installation of lalsuite.  The problem goes away if I do

import os
os.environ["OMP_NUM_THREADS"] = "1"

as the very first thing in pycbc_inspiral, and it returns if I move those lines after the other imports.

**Comment by cdcapano** [comment] 2015-08-27 10:38
Hi Alex, Larne,

Thanks for looking into this further. I'm a bit confused as to why my strace shows the system install of lalsimulation being loaded, since I installed lalsuite myself and made sure to source it before installing pycbc. If I source my install, then import lalsimulation in ipython, I get:
```
>>> import lalsimulation
>>> lalsimulation.__file__
    '/home/cdcapano/opt/local/lalsuite/bbh_aligned_spin_paper/lib/python2.7/site-packages/lalsimulation/__init__.pyc'
```
Which is the correct path.

When I look at strace.out, I noticed that it tries open lalsimulation in a number directories, doesn't find it, then eventually arrives at the system installation. Look at lines 23127-23222 of my strace.out file. The weird thing is, it never seems to try the actual directory I installed lalsimulation in, which is above. Double checking my PYTHONPATH does show my lalsimulation installed directory. I even tried reversing the order that I source lalsuite and pycbc (so, source pycbc first, then lalsuite, to get lalsuite's path first), and it made no difference.

I don't know if that helps any; even if it is mistakenly sourcing the system install of lalsimulation, it's still not clear as to why it's ignoring OMP_NUM_THREADS in that case.

Collin

**Comment by cdcapano** [comment] 2015-08-28 10:52
Hi Alex, Larne,

I was just running pycbc_inspiral by hand to track down another bug, and I found that if I copy the executable from pycbc/bin to a directory and run that, it *does* pick up my installed version of lalsuite. Specifically, while in the test directory I pointed you to earlier:
```
/home/cdcapano/overlapStudies/early_aligo/flow30Hz/M_4_50_bbh/ians_new_banks/geom_bank_6_1100_stoch_filled_2step/pycbc_workflow/run_mkl/test
```
I did the following:
```
cp ~/opt/src/pycbc/bin/pycbc_inspiral .
chmod +x pycbc_inspiral
strace -o strace4.out ./pycbc_inspiral  [arguments]
```
When I did that, I noticed I was getting error messages from lalsimulation that I wasn't getting before. Checking strace4.out, I see:
```
open("/home/cdcapano/opt/local/lalsuite/bbh_aligned_spin_paper/lib/python2.7/site-packages/lalsimulation/_lalsimulation.so", O_RDONLY) = 13
```
So now pycbc_inspiral is loading lalsimulation from my installed location, not from the system install. If I run the installed version of pycbc_inspiral, which is in:
```
/home/cdcapano/opt/local/pycbc/master/bin/pycbc_inspiral
```
I get the system installed version of lalsuite. I see that the installed version isn't actually pycbc_inspiral, but a script that calls a version of pycbc_inspiral:
```
#!/usr/bin/python
# EASY-INSTALL-SCRIPT: 'PyCBC===a5975e','pycbc_inspiral'
__requires__ = 'PyCBC===a5975e'
__import__('pkg_resources').run_script('PyCBC===a5975e', 'pycbc_inspiral')
```
This is apparently messing up the python path to lalsuite.

So, there appears to be two issues: 1. The installed version of pycbc_inspiral does not use the correct version of lalsuite. 2. For whatever reason, certain versions of lalsimulation cause omp to ignore OMP_NUM_THREADS set by pycbc_inspiral.

I haven't tried using virtualenv yet, so maybe the first issue is fixed by doing that. Still, even if it is, shouldn't it be possible to use pycbc without needing a virtual environment?

**Comment by lppekows** [comment] 2015-08-28 20:26
Hi Collin,

I think I understand issue (2).  libgomp looks for the environment variable at the time it is loaded.  So the chain of events should be 

1. Process command-line arguments
2. Set the environment variable
3. Dynamically load the libraries needed for the scheme which will: 
4. load libgomp, which will read the environment variable and all will be well

but what is happening is

1. The system lalsimulation is imported which:
2. loads libgomp, which looks for the environment variable and, not finding it, uses the default value
3. Process command line arguments
4. Set the environment variable, but it's too late and there's no way to tell libgomp to check again

As for issue (1), the wrapper is meant to ensure that the program has everything it needs at runtime.  I think the fact that it's pulling in the system install of lalsuite means that that's what was found at the time you built pycbc but I'm not certain.

While it might be worth thinking about how to make this more robust, I can almost guarantee that using the new build instructions will fix this, as well as a slew of other problems.  The virtual environment stuff isn't necessary, but a number of people at Syracuse have been using it this week and it's just plain better in every way.

**Comment by spxiwh** [comment] 2015-08-28 20:39
The first issue is possibly caused by the presence of the line:

/usr/lib/python2.7/dist-packages

in the file:

/home/cdcapano/opt/local/pycbc/bbh_aligned_spin_paper-updates/lib/python2.7/site-packages/easy-install.pth

I would remove that

**Comment by duncan-brown** [comment] 2015-08-29 12:31
Yes, this is exactly the kind of problem that the virtual environment install is meant to avoid. Collin, please try switching to that install, so you don't pick up the system installed lalsuite. If you still have issues, please let me know.

**Comment by duncan-brown** [comment] 2015-09-04 01:12
I am closing this as fixed, as the problem seemed to be Collin's environment.

**Comment by josh-willis** [comment] 2015-09-04 18:22
Hi Duncan,

I'm reopening this because while there was an issue with Collin's environment, it was only highlighting a problem that does in fact exist, but which we may or may not be able to do much about.

While the problem in Collin's environment did pull in an unintended system version of `lalsimulation`, if he had intentionally compiled `lalsimulation` with multithreaded support (as he might do, for example, if he were running multithreaded and wanted waveform generation to be multithreaded), then he would still hit this issue.

As Larne and Alex suspected, the real problem is that at least with GCC, the OpenMP library (`libgomp`) reads the environment variable `OMP_NUM_THREADS` once at startup, and then does not read it again.  Github doesn't seem to allow attaching a file, but I have pushed a branch `test_threads` to my repo, and added a simple script that demonstrates the issue using only `pycbc.scheme` and weave code. There is a script https://github.com/josh-willis/pycbc/blob/test_threads/tools/tests/thread_change.py that defines a simple parallel function, and calls it once before entering the user specified context, and once after.  If I do:
```
./thread_change.py --processing-scheme cpu:2`
```
then I get the output:
```
Total number of threads is 12
Total number of threads is 12
```
on atlas8.  But if I comment out the call to `print_total_threads()` before the context block, then I get:
```
Total number of threads is 2
```
as expected.

I'll assign this to me, but there may be no portable way to fix this that does not rely on multithreaded code explicitly knowing about the environment variable, or some other way of setting it. In which case we can update the documentation and close this issue again.

**Comment by josh-willis** [comment] 2015-09-04 20:25
Pull request #249  hopefully has a fix for this; @cdcapano , can you still check if it fixes your original problem?

**Comment by josh-willis** [comment] 2015-09-08 17:23
Closing as #249 has been approved and merged.

**Closed by josh-willis** 2015-09-08 17:23 UTC
