### ISSUE TITLE
software injection into a TimeSeries of zeroes is not tapered as expected

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#186] opened 2015-08-06 14:34 UTC
I was doing software injections into a TimeSeries of zeroes.

I'm using `pycbc.inject.InjectionSet.apply` (ie. what we use to do software injections in `pycbc_inspiral`). But the `EOBNRv2` waveform that is supposed to be tapered looks like: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/nottapered.png

I did a little digging and here's what I've looked at so far. The function call that actually generates the waveform timeseries is `lalsimulation.SimDetectorStrainREAL8TimeSeries` (called via `pycbc.detector.project_wave`).

`lalsimulation.SimDetectorStrainREAL8TimeSeries` adds these little bits of noise at the start of the waveform timeseries. I saved the output in `inject.py` and it coming from this function call. There is some padding and interpolation that happens here, maybe needs a closer look.

Then this waveform timeseries is tapered with `SimInspiralREAL8WaveTaper` (called via `pycbc.waveform.utils.taper_timeseries`). Now the algorithm in `SimInspiralREAL8WaveTaper` is to taper to the second peak in the waveform. So these little bits of noise add a bunch of little peaks and `SimInspiralREAL8WaveTaper` tapers just a couple noise peaks.

Note if the waveform just abruptly ends then there is no problem with `SimInspiralREAL8WaveTaper`, it works as its suppose to. However these little noise bits cause a problem.

For the plot above the following injection file on sugar was used: `/home/cbiwer/projects/pycbc_test_inject/issue/injection.xml.gz`
And the following script on sugar to make the plot: `/home/cbiwer/projects/pycbc_test_inject/issue/pycbc_test_inject`

Maybe I'm doing something weird here but I'm a bit suspicious about the taper of our injections now.

**Comment by cmbiwer** [comment] 2015-08-06 19:13
In the documentation of `LALSimulation.c` it says:
> A 19-sample Welch-windowed sinc kernel is used for sub-sample interpolation.

And it is interpolating the two polarizations of the waveform, it looks like this is the culprit. I believe this is the filter that is ringing up/down in our software injection timeseries.

The routine that does the interpolation is `XLALREAL8TimeSeriesInterpEval`.

Zeroing out the length of the filter fixes the issue.

**Comment by titodalcanton** [comment] 2015-08-06 20:18
Hi Chris, I remember hitting a very similar issue many months ago. I thought that was fixed with a change in LAL. I assume you're using an up-to-date LAL, so it's quite interesting that the bug popped back again.

**Comment by titodalcanton** [comment] 2015-08-06 20:20
I believe this was Tom's fix for the issue I mentioned:
https://ligo-vcs.phys.uwm.edu/cgit/lalsuite/commit/?id=5c7f7e7de099858a2d334a5e432f87ced1346a35

**Comment by tdent** [comment] 2015-08-06 21:07
Indeed, I hoped that the fix I put in would work, but maybe there are occasional issues .. 
Chris, can you plot the waveform in much finer time resolution around the time of the abrupt jump, with x-axis = sample number? 
Also could you plot the waveform you get by *not* asking for tapering?

**Comment by cmbiwer** [comment] 2015-08-06 22:31
Hey thanks for the responses . I'm using githash `3dc971a085afdbf06b44fb463ed08036270bf377` (July 2015) so its fairly recent.

Here's a plot of taper vs. no taper using master: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/tapernotaper.png

Blue: Tapered
Green: Not tapered

**Comment by tdent** [comment] 2015-08-07 11:48
Hi Chris - interesting .. I must have not quite thought through all the possible cases, since it should have been fairly clear that there could be ringing producing spurious maxima and minima both before and after the jump (depending on the initial phase). 
Chris, can you change 
const UINT4 LALSIMULATION_RINGING_EXTENT = 9;
to 
const UINT4 LALSIMULATION_RINGING_EXTENT = 19;
in lalsimulation/src/LALSimInspiralWaveformTaper.c , rebuild LALSimulation and see if that fixes the issue?

**Comment by cmbiwer** [comment] 2015-08-07 19:39
Hey Tom, I changed `LALSIMULATION_RINGING_EXTENT` to 19 and it doesn't appear to correct the problem. Also I edited githash `69974be4500c7235ea93b2a80a0bce6bec316b45` this time. Though it doesn't appear to have tapered anything at all, which is weird.

Here's a plot of the waveform with the extent set to 19: https://sugar-jobs.phy.syr.edu/~cbiwer/tmp/window19.png

**Comment by tdent** [comment] 2015-08-09 11:44
OK, that's strange.  Let me see if I can reproduce the issue ..

**Comment by tdent** [comment] 2015-08-09 13:35
Chris, I can't reproduce the issue.  Using a rebuilt lalsimulation I actually get an error with your injection file:
```
XLAL Error - XLALSimInspiralDecomposeWaveformString (LALSimInspiral.c:4682): Invalid waveform string `EOBNRv2'. 
XLAL Error - XLALGetOrderFromString (LALSimInspiral.c:4752): Cannot parse approximant from string `EOBNRv2'. 
XLAL Error - XLALGetOrderFromString (LALSimInspiral.c:4752): Invalid argument
```

I think this is due to a change Jolien made some months ago to make the string parsing more picky. 
If I then switch 'EOBNRv2' out for 'EOBNRv2pseudoFourPN' I don't get an error: then with the LALSIMULATION_RINGING_EXTENT constant

**Comment by cmbiwer** [comment] 2015-08-11 20:27
Ok so I was able to reproduce your plot with `LALSIMULATION_RINGING_EXTENT`set to 19, and it looks like this is another solution.

I think when I rebuilt master the errors in lalframe (see list) stopped my install of lalsuite and I probably just picked up the system installed lalsimulation.

I suppose we can close my PR here in pycbc and make a PR in lalsimulation to switch `LALSIMULATION_RINGING_EXTENT` from 9 to 19.

**Comment by tdent** [comment] 2015-08-11 20:56
Thanks Chris .. well, there are various unexpected things that can happen when rebuilding lalsuite, depending on the way you do it.  
We can use the old redmine issue (https://bugs.ligo.org/redmine/issues/1766) to deal with this .. you may have to sign up as a developer in lalsimulation to post there, ask Adam M.

**Closed by tdent** 2015-08-11 20:56 UTC
